// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBee7Vt_P9EJRBIyw5Lt9dCKnC5eEE0kng',
    appId: '1:248555738754:web:5e020cc668eee81f9b069b',
    messagingSenderId: '248555738754',
    projectId: 'driverapp-401313',
    authDomain: 'driverapp-401313.firebaseapp.com',
    storageBucket: 'driverapp-401313.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP-6wt2lkDyjdp_c8N322CiFajjCrryB4',
    appId: '1:248555738754:android:f7d7056a3b021f1d9b069b',
    messagingSenderId: '248555738754',
    projectId: 'driverapp-401313',
    storageBucket: 'driverapp-401313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-IyaS6pXe7r39P5V1_US1_BoBGNNQHg',
    appId: '1:248555738754:ios:f91ed9c6523e3d4a9b069b',
    messagingSenderId: '248555738754',
    projectId: 'driverapp-401313',
    storageBucket: 'driverapp-401313.appspot.com',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ-IyaS6pXe7r39P5V1_US1_BoBGNNQHg',
    appId: '1:248555738754:ios:cac4e9b7e47a57ce9b069b',
    messagingSenderId: '248555738754',
    projectId: 'driverapp-401313',
    storageBucket: 'driverapp-401313.appspot.com',
    iosBundleId: 'com.example.taxiApp.RunnerTests',
  );
}
